### ISSUE TITLE
Use @content in base template?

### ISSUE THREAD

**Issue by cycomachead** [bromagosa/SnapSite#24]
I’m wondering why the base template doesn’t make use of this? The current version seems a little more confusing to have the file split in 2. 

I could guess it’s something about the file getting hard to read. If that’s the case can we build an `@include=` option for templates to include other templates?
That would let us structure the file a little more clearly.

**Comment by bromagosa** [comment]
It was a quick hack. Remember this is not ready at all. I'm waiting for funding to finish the site.

Your change makes perfect sense though, and it's something I wanted to end up implementing. Thanks!

**Comment by cycomachead** [comment]
Fixed with #26
