### ISSUE TITLE
Allow users to delete their own account

### ISSUE THREAD

**Issue by bromagosa** [bromagosa/SnapSite#30]
Showing an additional confirmation dialog and asking for password.

**Comment by bromagosa** [comment]
@cycomachead what do we do with users that have projects? Should we delete them too?

Is it maybe time to implement Brian's suggestion to never actually delete a project, but just mark it as deleted (or move it into a DELETED table)?

**Comment by cycomachead** [comment]
Perhaps moving it to a deleted table is a good idea. 

I think GDPR technically requires us to permanently delete some data after some time. I think a deleted table works well enough and then we can just clear that out every so many days or something?

**Comment by bromagosa** [comment]
Right, and what do we do with the actual projects then? Keep them until we clear the table?

**Comment by cycomachead** [comment]
I think the idea of keeping the table around is to allow recovering from mistakes. So, in that case, I think it makes to keep the project files. Then when you clear a row from the deleted table is also when you clear the data from the disk.

**Comment by bromagosa** [comment]
Done in https://github.com/bromagosa/snapCloud/commit/dcfe709d4a7e14bc693ae29fd3a38f9d866a9b7c
