### ISSUE TITLE
Flag a project

### ISSUE THREAD

**Issue by bromagosa** [bromagosa/SnapSite#34]
Just adds it to the `flagged` collection, owned by some user still to determine. @cycomachead, should we create the "system" user or something like this? We could use it for this collection but also for things like featured projects, team favorites, etc.

**Comment by cycomachead** [comment]
https://cloud.snap.berkeley.edu/site/user?user=snapcloud

Is a snapcloud user I made. Maybe that can be our "system" user? Seems more friendly than 'admin' or something.

I think a system account for curated collections works well.

**Comment by bromagosa** [comment]
Cool, this is where featured projects live now:

https://cloud.snap.berkeley.edu/site/collection?user=snapcloud&collection=Featured

I'm quite exhausted now, but tomorrow I'll work on public & published flags, as well as thumbnails. Following your workflow, I'm adding issues for those ;)

**Comment by bromagosa** [comment]
Done :)
